### ISSUE TITLE
Flood fill edge case

### ISSUE THREAD

**Issue by sparklebutt** [FjjDessoyCaraballo/cub3d#3]
As of commit eb349919e85e5279a9b6054eaca87cd85b8f3962 our program has a flood fill, but the flood fill might not be handling this edge case:

![image](https://github.com/user-attachments/assets/05b37f5c-599b-4a04-9da1-3555a4c734f9)

Where the player is, the flood fill will do its work, but the problem lies on outside the walled off area of the player. It still constitutes part of the map, but its not completely walled off, therefore, a failure for our project.

**Comment by FjjDessoyCaraballo** [comment]
As of commit 17ec06c0493074abda81c7461cf9fd777220c5dc we are checking for all rooms inside a map.

If the player would be walled off,  but a room inside the wouldn't be, such as:

```
1111111
1N01000
1111111
```
The map would still be acceptable as the `flood fill` would be only checking for the position of the player. With the new addition of the function `check_if_walled()` now we check any remainder "room" that would'nt be walled off. For further testing, check inside the maps directory for `not_walled3.cub` and run the tester script `tests.sh` inside the same directory
